from selenium.webdriver.common.by import By


class MainPageLocators:
    PERSONAL_ACCOUNT = (By.XPATH, "//*[text()='Личный Кабинет']")
    CONSTRUCTOR = (By.XPATH, "//p[text()='Конструктор']")
    ASSEMBLE_THE_BURGER_TEXT = (By.XPATH, "//h1[text()='Соберите бургер']")
    ORDER_FEED_BUTTON = (By.XPATH, "//p[text()='Лента Заказов']")
    ORDER_FEED_TEXT = (By.XPATH, "//h1[text()='Лента заказов']")
    INGREDIENT_DETAILS_TEXT1 = (By.XPATH, "//h2[text()='Детали ингредиента']")
    SECTION_LOCATOR = (By.XPATH, "//section[contains(@class, 'Modal_modal__P3_V5')]")
    SECTION_OPEN_LOCATOR = (By.XPATH, "//section[contains(@class, 'Modal_modal_opened')]")
    BUN = (By.XPATH, "//a[@class='BurgerIngredient_ingredient__1TVf6 ml-4 mr-4 mb-8']")
    SOUSE = (By.CSS_SELECTOR, "img[alt='Соус Spicy-X']")
    COUNTER_OF_SOUSE = (By.XPATH, "//a[img[@alt='Соус Spicy-X']]/div/p")
    CROSS_IN_MODAL_WINDOW = (By.CSS_SELECTOR, "button[type='button'][class^='Modal_modal__close']")
    TARGET_PLACE = (By.CSS_SELECTOR, "ul[class*='basket__list']")
    ORDER_IN_ORDER_FEED = (By.CSS_SELECTOR, "li[class^='OrderHistory_listItem']")
    CREATE_ORDER_BUTTON = (By.XPATH, "//button[contains(text(), 'Оформить заказ')]")
    CREATE_ORDER_BUTTON1 = (By.CSS_SELECTOR, "button[class*='button_button']")
    NUMBER_OF_ORDER_AFTER_CREATE_ORDER = (By.XPATH, "//h2[contains(@class, 'Modal_modal__title_shadow')]")
    ORDER_STATUS_BOX = (By.XPATH, "//div[contains(@class,'OrderFeed_orderStatusBox')]")
    COUNTERS_OF_CREATED = (By.CSS_SELECTOR, "p[class^='OrderFeed_number']")
    ORDER_NUMBER_AT_WORK = (By.CSS_SELECTOR, "ul[class^='OrderFeed_orderListReady']")
    ORDER_NUMBER_AT_WORK1 = (By.CSS_SELECTOR, "ul[class^='OrderFeed_orderListReady'] > li[class^='text text_type_digits']")
    ORDER_NUMBER_AT_WORK2 = (By.XPATH, "//ul[contains(@class, 'OrderFeed_orderListReady')]/li")
    MODAL_WINDOW = (By.XPATH, "//div[contains(@class, 'Modal_modal_overlay__x2ZCr')]")
    MODAL_WINDOW2 = (By.CLASS_NAME, 'Modal_modal_overlay__x2ZCr')
    MODAL_WINDOW3 = (By.XPATH, "//div[contains(@class, 'Modal_modal__P3_V5')]/div")
    LOGO = (By.XPATH, "//div[contains(@class, 'header__logo')]")