from selenium.webdriver.common.by import By


class MainPageLocators:
    personal_account = (By.XPATH, "//*[text()='Личный Кабинет']")
    constructor = (By.XPATH, "//p[text()='Конструктор']")
    assemble_the_burger_text = (By.XPATH, "//h1[text()='Соберите бургер']")
    order_feed_button = (By.XPATH, "//p[text()='Лента Заказов']")
    order_feed_text = (By.XPATH, "//h1[text()='Лента заказов']")
    ingredient_details_text = (By.XPATH, "//h2[text()='Детали ингредиента']")
    section_locator = (By.XPATH, "//section[contains(@class, 'Modal_modal__P3_V5')]")
    section_open_locator = (By.XPATH, "//section[contains(@class, 'Modal_modal_opened')]")
    bun = (By.XPATH, "//a[@class='BurgerIngredient_ingredient__1TVf6 ml-4 mr-4 mb-8']")
    souse = (By.CSS_SELECTOR, "img[alt='Соус Spicy-X']")
    counter_of_souse = (By.XPATH, "//a[img[@alt='Соус Spicy-X']]/div/p")
    cross_in_modal_window = (By.CSS_SELECTOR, "button[type='button'][class^='Modal_modal__close']")
    target_place = (By.CSS_SELECTOR, "ul[class*='basket__list']")
    order_in_order_feed = (By.CSS_SELECTOR, "li[class^='OrderHistory_listItem']")
    create_order_button = (By.XPATH, "//button[contains(text(), 'Оформить заказ')]")
    create_order_button1 = (By.CSS_SELECTOR, "button[class*='button_button']")
    number_of_order_after_create_order = (By.XPATH, "//h2[contains(@class, 'Modal_modal__title_shadow')]")
    order_status_box = (By.XPATH, "//div[contains(@class,'OrderFeed_orderStatusBox')]")
    counters_of_created = (By.CSS_SELECTOR, "p[class^='OrderFeed_number']")
    order_number_at_work = (By.CSS_SELECTOR, "ul[class^='OrderFeed_orderListReady']")
    order_number_at_work1 = (By.CSS_SELECTOR, "ul[class^='OrderFeed_orderListReady'] > li[class^='text text_type_digits']")
    order_number_at_work2 = (By.XPATH, "//ul[contains(@class, 'OrderFeed_orderListReady')]/li")
